App:App.c add.c sub.c mul.c div.c mod.c Arith.h
	gcc App.c -o App libArith.so.1	


add.o:add.c
	gcc -c add.c -o add.o

sub.o:sub.c
	gcc -c sub.c -o sub.o

mul.o:mul.c
	gcc -c mul.c -o mul.o

div.o:div.c
	gcc -c div.c -o div.o

mod.o:mod.c
	gcc -c mod.c -o mod.o


